---
states:
#  Alabama:
#    url: 'http://alabamapublichealth.gov/infectiousdiseases/2019-coronavirus.html'
#    headerRowsToSkip: 1
#    countyCol: 'County of Residence'
#    footerRowsToSkip: 1
#  Alaska:
#    url: 'http://dhss.alaska.gov/dph/Epi/id/Pages/COVID-19/monitoring.aspx'
#    countyCol: 'Region'
#    footerRowsToSkip: 1
#    casesCol: 'Total'
#  Delaware:
#    type: 'api-json'
#    url: 'https://services1.arcgis.com/PlCPCPzGOwulHUHo/arcgis/rest/services/DEMA_COVID_County_Boundary_View/FeatureServer/0/query?f=json&where=NAME<>%27%27&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/NAME'
#    casesDpath: 'attributes/Presumptive_Positive'
#    deathsDpath: 'attributes/Total_Death'
#    recoveredDpath: 'attributes/Recovered'
#  Georgia:
#    url: 'https://dph.georgia.gov/covid-19-daily-status-report'
#    tableIndex: 2
#  Hawaii:
#    url: 'https://health.hawaii.gov/docd/advisories/novel-coronavirus-2019/'
#    headerRowsToSkip: 2
#    footerRowsToSkip: 4
#    casesCol: 'Unnamed: 1'
#  Idaho:
#    url: 'https://coronavirus.idaho.gov/'
#    footerRowsToSkip: 1
#  Indiana:
#    type: 'api-json'
#    url: 'https://services5.arcgis.com/f2aRfVsQG7TInso2/arcgis/rest/services/County_COVID19/FeatureServer/0/query?f=json&where=COUNTYNAME%3C%3E%27%27&returnGeometry=false&outfields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/COUNTYNAME'
#    casesDpath: 'attributes/Total_Positive'
#    deathsDpath: 'attributes/Total_Deaths'
#  Iowa:
#    type: 'api-json'
#    url: 'https://services.arcgis.com/vPD5PVLI6sfkZ5E4/arcgis/rest/services/IA_COVID19_Cases/FeatureServer/0/query?f=json&where=Name%3C%3E%27%27&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/Name'
#    casesDpath: 'attributes/Confirmed'
#    deathsDpath: 'attributes/Deaths'
#    recoveredDpath: 'attributes/Recovered'
#  Lousiana:
#    type: 'api-json'
#    url: 'https://services5.arcgis.com/O5K6bb5dZVZcTo5M/arcgis/rest/services/Cases_by_Parish_2/FeatureServer/0/query?f=json&where=PFIPS%20%3C%3E%2099999&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/Parish'
#    casesDpath: 'attributes/Cases'
#    deathsDpath: 'attributes/Deaths'
#  Maine:
#    url: 'https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus.shtml'
#    tableIndex: 1
#    headerRowsToSkip: 2
#    casesCol: 'Confirmed'
#  Maryland:
#    type: 'api-json'
#    url: 'https://services.arcgis.com/njFNhDsUCentVYJW/arcgis/rest/services/COVID19_MD_CountyCaseCounts_DEMO/FeatureServer/0/query?f=json&where=COUNTY%3C%3E%27%27&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/COUNTY'
#    casesDpath: 'attributes/COVID19Cases'
#    deathsDpath: 'attributes/COVID19Deaths'
#    recoveredDpath: 'attributes/COVID19Recovered'
#  Michigan:
#    url: 'https://www.michigan.gov/coronavirus/0,9753,7-406-98163-520743--,00.html'
#    footerRowsToSkip: 1
#  Minnesota:
#    url: 'https://www.health.state.mn.us/diseases/coronavirus/situation.html'
#  Mississippi:
#    url: 'https://msdh.ms.gov/msdhsite/_static/14,0,420.html#Mississippi'
#    footerRowsToSkip: 1
#  Missouri:
#    url: 'https://health.mo.gov/living/healthcondiseases/communicable/novel-coronavirus/results.php'
#    casesCol: 'Total'
#  Montana:
#    type: 'api-json'
#    url: 'https://services.arcgis.com/qnjIrwR8z5Izc0ij/arcgis/rest/services/PUBLIC_VIEW_COVID19_CASES/FeatureServer/0/query?f=json&where=NAME%3C%3E%27%27&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/NAMELABEL'
#    casesDpath: 'attributes/Total'
#  New Jersey:
#    type: 'api-json'
#    url: 'https://services7.arcgis.com/Z0rixLlManVefxqY/arcgis/rest/services/DailyCaseCounts/FeatureServer/0/query?f=json&where=COUNTY_LAB%3C%3E%27%27&returnGeometry=false&outFields=*'
#    countyListDpath: 'features'
#    countyDpath: 'attributes/COUNTY_LAB'
#    casesDpath: 'attributes/COUNTS'
#  New Mexico:
#    url: 'https://cv.nmhealth.org/cases-by-county/'
#  New York:
#    url: 'https://coronavirus.health.ny.gov/county-county-breakdown-positive-cases'
#    casesCol: 'Positive Cases'
#    footerRowsToSkip: 1
#  Oklahoma:
#    url: 'https://coronavirus.health.ok.gov'
#    footerRowsToSkip: 1
#    casesCol: 'COVID-19 Cases by County*'
#    tableIndex: 3
#  Oregon:
#    url: 'https://govstatus.egov.com/OR-OHA-COVID-19'
#    casesCol: 'Number of cases'
#    footerRowsToSkip: 1
#    tableIndex: 1
#  Pennsylvania:
#    url: 'https://www.health.pa.gov/topics/disease/coronavirus/Pages/Cases.aspx'
#    tableIndex: 1
#  South Dakota:
#    url: 'https://doh.sd.gov/news/Coronavirus.aspx'
#    tableIndex: 2
#    casesCol: '# of Cases'
#    footerRowsToSkip: 1
#  Tennessee:
#    url: 'https://www.tn.gov/health/cedep/ncov.html'
#    casesCol: 'Count'
#    tableIndex: 1
#    footerRowsToSkip: 1
#  Texas:
#    url: 'https://www.dshs.state.tx.us/news/updates.shtm#coronavirus'
#    casesCol: 'Number of Cases3'
#    countyCol: 'County of Residence2'
#    tableIndex: 2

nopage:
  - Arizona
  - Arkansas
  - California
  - Colorado
  - Kentucky
  - Nebraska
  - Nevada
  - New Hampshire
  - Rhode Island
  - Vermont

jsrender:
  - Colorado 'https://public.tableau.com/profile/cocdphe.svc#!/vizhome/COVID19_CaseSummary/COVID-19CaseSummary'

pdf:
  Connecticut
  Florida 'https://floridadisaster.org/globalassets/covid19/dailies/covid-19-data---daily-report-2020-03-22-0951.pdf'
  Kansas 'https://khap2.kdhe.state.ks.us/NewsRelease/COVID19/COVID-19_March_21_2020_.pdf'
  Massassachusetts 'https://www.mass.gov/doc/covid-19-cases-in-massachusetts-as-of-march-21-2020/download'

map:
  - Illinois 'http://www.dph.illinois.gov/topics-services/diseases-and-conditions/diseases-a-z-list/coronavirus'

other:
  DC 'https://coronavirus.dc.gov/page/coronavirus-data'
  New Jersey 'https://covid19.nj.gov/'
  North Carolina 'https://www.ncdhhs.gov/covid-19-case-count-nc'
  North Dakota 'https://www.health.nd.gov/diseases-conditions/coronavirus/north-dakota-coronavirus-cases'
  Ohio 'https://coronavirus.ohio.gov/wps/portal/gov/covid-19/'
  South Carolina 'https://www.scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/monitoring-testing-covid-19, https://www.scdhec.gov/infectious-diseases/viruses/coronavirus-disease-2019-covid-19/additional-data-covid-19'
  Utah 'https://coronavirus.utah.gov/case-counts/'
  Virginia 'http://www.vdh.virginia.gov/coronavirus/'
  Washington 'https://www.doh.wa.gov/Emergencies/Coronavirus'
  West Virginia 'https://dhhr.wv.gov/COVID-19/Pages/default.aspx'
  Wisconsin 'https://www.dhs.wisconsin.gov/outbreaks/index.htm'
  Wyoming 'https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/'
  Puerto Rico 'https://estadisticas.pr/en/covid-19'
  Guam 'http://dphss.guam.gov/2019-novel-coronavirus-2019-n-cov/'
  US Virgin Islands 'https://doh.vi.gov/'

none:
  Northern Mariana Islands
  American Samoa
  Republic of Palau
  Micronesia
  Marshall Islands